### PR TITLE
download pre-built slirp4netns binary (v1.1.4)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Required for https://github.com/rancher/k3s/issues/1709

Replace #6 #11

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@ibuildthecloud @erikwilson PTAL

**Comment by AkihiroSuda** [comment]
Ping @ibuildthecloud @erikwilson

**Comment by AkihiroSuda** [comment]
updated to v1.1.4

**Comment by brandond** [comment]
@AkihiroSuda I'll see about getting k3s-root updated in k3s, but I think the next couple days are going to be busy with release stuff so it might be a bit.

**Pull request merged**
