### PR TITLE
Use blkid from util-linux instead of busybox

### PR DESCRIPTION
**Pull request by brandond**
Fixes https://github.com/rancher/k3s/issues/1682

### CODE REVIEW

**Comment by brandond** [comment]
Hmm, it turns out we also need CONFIG_FEATURE_BLKID_TYPE. I'm not convinced this would have worked for other non-xfs filesystems either, since without this feature blkid doesn't output the type field at all.

**Comment by brandond** [comment]
Turns out even after fixing the busybox config to include the correct features, busybox still doesn't support the `-o export` option that switches the output format to what k8s expects:

```
root@seago:~# /var/lib/rancher/k3s/data/a7980570cdf38ca59f5bd216a8027076105082689cefc85290137dfcca0ffac2/bin/blkid -p -s TYPE -s PTTYPE -o export /dev/sdi
/dev/sdi: UUID="11a2af42-00c9-4660-917f-191d45679885" TYPE="xfs"
```

```
root@seago:~# blkid -p -s TYPE -s PTTYPE -o export /dev/sdi
DEVNAME=/dev/sdi
TYPE=xfs
```

I'm not quite sure where to go from here.

**Comment by brandond** [comment]
OK, turns out it was easy enough to replace blkid from busybox with util-linux.

**Comment by ibuildthecloud** [comment]
LGTM.  Thanks @brandond!!

**Pull request merged**
